In [1]:
import numpy as np
n6=np.linspace(1,100,30).reshape(15,2)
print(n6)

[[  1.           4.4137931 ]
 [  7.82758621  11.24137931]
 [ 14.65517241  18.06896552]
 [ 21.48275862  24.89655172]
 [ 28.31034483  31.72413793]
 [ 35.13793103  38.55172414]
 [ 41.96551724  45.37931034]
 [ 48.79310345  52.20689655]
 [ 55.62068966  59.03448276]
 [ 62.44827586  65.86206897]
 [ 69.27586207  72.68965517]
 [ 76.10344828  79.51724138]
 [ 82.93103448  86.34482759]
 [ 89.75862069  93.17241379]
 [ 96.5862069  100.        ]]


In [4]:
n5=np.arange(1,100,20)
print(n5)

[ 1 21 41 61 81]


In [7]:
np.random.randint(1,100,10)

array([26, 91, 10, 23, 97, 34,  6,  7, 35,  2])

In [10]:
ne=np.random.randint(0,9,(3,3))
print(ne)

[[6 4 4]
 [3 3 8]
 [7 8 3]]


In [21]:
np.random.permutation(100).reshape(10,10)

array([[ 2, 72, 60, 49, 67, 35, 12, 18,  5, 32],
       [41, 11, 26, 86, 87,  6, 68, 78, 76, 14],
       [31, 42, 63, 36, 88, 98, 90, 77, 21, 23],
       [97, 91, 24,  4, 94, 13, 81, 56, 20, 16],
       [64, 17, 44, 45, 33,  7,  0, 59, 46, 62],
       [39, 82, 47, 53, 27, 93, 80, 37, 69, 43],
       [84, 73, 51, 19, 25, 83, 28, 30,  1,  3],
       [54, 79, 57, 71, 85,  9, 65, 66, 89, 15],
       [95, 40, 99, 29, 74, 52, 92, 22,  8, 96],
       [58, 70, 50, 61, 55, 75, 10, 34, 48, 38]])

In [16]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [27]:
x=np.array([1,2,3])
y=np.array([4,5,6])
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x%y)
print(x//y)
print(np.dot(x,y))
print(np.cross(x,y))
print(np.inner(x,y))
print(np.outer(x,y))
print(np.matmul(x,y))



[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 2 3]
[0 0 0]
32
[-3  6 -3]
32
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
32


In [28]:
x=np.array([1,2,3,4,5,6,7,8])
print(x.sum())#sum
print(x.mean())#mean
print(x.std())#standad deviation
print(x.var())#variance
print(x.min())#minimum
print(x.max())#maximum
print(x.argmin())#index of minimum
print(x.argmax())#index of maximum
print(x.cumsum())#cumulative sum
print(x.cumprod())# cumilative product

36
4.5
2.29128784747792
5.25
1
8
0
7
[ 1  3  6 10 15 21 28 36]
[    1     2     6    24   120   720  5040 40320]


In [31]:
x=np.array([0,30,45,60,90])
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))
print(np.deg2rad(x))

[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]
[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362]
[ 0.         -6.4053312   1.61977519  0.32004039 -1.99520041]
[0.         0.52359878 0.78539816 1.04719755 1.57079633]


In [41]:
x=np.arange(100).reshape(10,10)
print(x)
print(x[0])#first row
print(x[3,5])#element ar row 5 and coloumn 5
print(x[:,0])#first column
print(x[:3,-1]) #first 3 rows last column
print(x[:3,3]) #first 3 rows first 3 columns
print(x[:,[2,4,6]])#columns 2,4,6

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[0 1 2 3 4 5 6 7 8 9]
35
[ 0 10 20 30 40 50 60 70 80 90]
[ 9 19 29]
[ 3 13 23]
[[ 2  4  6]
 [12 14 16]
 [22 24 26]
 [32 34 36]
 [42 44 46]
 [52 54 56]
 [62 64 66]
 [72 74 76]
 [82 84 86]
 [92 94 96]]


In [43]:
np.nan #not a number (missing value)

nan

In [44]:
np.inf# infinity

inf